version: '3.7'
services:
  api:
    build:
      context: ./the-pattern-api/
      dockerfile: Dockerfile
    container_name: the-pattern-api
    entrypoint: ["/usr/local/bin/gunicorn"]
    command:  --bind 0.0.0.0:8080 -w 10 wsgi:app
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - ./.env.prod
    depends_on:
      - redisgraph

  redisgraph:
    image: redislabs/redisgraph
    container_name: redisgraph
    hostname: redisgraph
    volumes:
      - ./data/redis_data:/data
      - ./the-pattern-platform/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - /usr/local/etc/redis/redis.conf
    ports:
      - 127.0.0.1:9001:6379
    env_file:
      - ./.env.prod

  rgcluster:
    build:
      context: ./the-pattern-platform/conf/
      dockerfile: Dockerfile_redisai
    container_name: rgcluster
    hostname: rgcluster
    volumes:
      - ./the-pattern-platform/conf/docker-config_prod.sh:/cluster/config.sh
    ports:
      - 127.0.0.1:30001:30001
      - 127.0.0.1:30002:30002
      - 127.0.0.1:30003:30003
      - 10.144.17.211:30004:30004
      - 10.144.17.211:30005:30005
      - 10.144.17.211:30006:30006
      - 10.144.17.211:30007:30007
      - 10.144.17.211:30008:30008
      - 10.144.17.211:30009:30009
      - 10.144.17.211:30010:30010

